
export const VideosObj = {
    Thumbnail1: "./src/pages/YT front page/components/videoAssets/okz263qlhv7a1.jpg",
    Duration1: "10:05",
    Title1: "SsethTzeentach - YouTube",
    CreatorImg1: "./src/pages/YT front page/components/videoAssets/creators/SsethTzeentach.jpg",
    Creator1: "SsethTzeentach",
    Views1: "13M views",
    Age1: "6 years ago",
    
    Thumbnail2: "./src/pages/YT front page/components/videoAssets/Men-on-Men-actions.jpg",
    Duration2: "20:13",
    Title2: "Warlords Battlecry III Review | Losing It™",
    CreatorImg2: "./src/pages/YT front page/components/videoAssets/creators/SsethTzeentach.jpg",
    Creator2: "SsethTzeentach",
    Views2: "6M views",
    Age2: "4 years ago",
    
    Thumbnail3: "./src/pages/YT front page/components/videoAssets/26e973fd5f268cb711c9104562f4b57d.png",
    Duration3: "0:53",
    Title3: "Xi Jinping vows China will never be bullied during anniversary speech",
    CreatorImg3: "./src/pages/YT front page/components/videoAssets/creators/channels4_profile.jpg",
    Creator3: "South China Morning Post",
    Views3: "354K views",
    Age3: "3 years ago",

    Thumbnail4: "./src/pages/YT front page/components/videoAssets/CAESAR.jpg",
    Duration4: "0:51",
    Title4: "Agent Combat Intel: Caesar | Zenless Zone Zero",
    CreatorImg4: "./src/pages/YT front page/components/videoAssets/creators/Asmon.jpg",//"./src/pages/YT front page/components/videoAssets/creators/ZZZ.jpg",
    Creator4: "Zenless Zone Zero",
    Views4: "135k views",
    Age4: "2 years ago",

    Thumbnail5: "./src/pages/YT front page/components/videoAssets/WH40K.jpg",
    Duration5: "10:05",
    Title5: "Space Marine 2 Is A Masterpiece",
    CreatorImg5: "src/pages/YT front page/components/videoAssets/creators/penguinz0.jpg",
    Creator5: "penguinz0",
    Views5: "910K views",
    Age5: "10 days ago",

    Thumbnail6: "./src/pages/YT front page/components/videoAssets/Moist-dad.jpg",
    Duration6: "0:35",
    Title6: "Penguinz0 Laughing hysterically at his Markiplier Art",
    CreatorImg6: "./src/pages/YT front page/components/videoAssets/creators/penguinz0.jpg",
    Creator6: "penguinz0",
    Views6: "10M",
    Age6: "2 years ago",

    Thumbnail7: "./src/pages/YT front page/components/videoAssets/jschlatt-what-you-thinkin-v0-bj1h5vqfghua1.png",
    Duration7: "12:02",
    Title7: "Schlagg's 9/11 compilation",
    CreatorImg7: "./src/pages/YT front page/components/videoAssets/creators/jschlatt.jpg",
    Creator7: "Schlagg",
    Views7: "1.2M views",
    Age7: "11 months ago",

    Thumbnail8: "./src/pages/YT front page/components/videoAssets/ChangliWuWa.jpg",
    Duration8: "3:20",
    Title8: "Wuthering Waves | Resonator Showcase | Changli — SEIZE THE INITIATIVE",
    CreatorImg8: "./src/pages/YT front page/components/videoAssets/creators/Bwad.jpg",//"./src/pages/YT front page/components/videoAssets/creators/WuwWa.jpg",
    Creator8: "Wuthering Waves",
    Views8: "2.5M views",
    Age8: "1 month ago",

    Thumbnail9: "./src/pages/YT front page/components/videoAssets/hq720.jpg",
    Duration9: "5:32",
    Title9: "League of Legends Review | 4K Edition™",
    CreatorImg9: "./src/pages/YT front page/components/videoAssets/creators/SsethTzeentach.jpg",
    Creator9: "SsethTzeentach",
    Views9: "728K views",
    Age9: "1 day ago",

    ShortThumbnail1: "./src/pages/YT front page/components/videoAssets/Waltuh.jpg",
    ShortTitle1: "jesse leveling up his science knowledge | Breaking Bad",
    ShortViews1: "364K views",

    ShortThumbnail2: "./src/pages/YT front page/components/videoAssets/FoPkbm7XoAAu8fX.jpg",
    ShortTitle2: "Silence Fag, Biden blast",
    ShortViews2: "3.4M views",

    ShortThumbnail3: "./src/pages/YT front page/components/videoAssets/ghost.jpg",
    ShortTitle3: "Ghost - Metamorphosis",
    ShortViews3: "3.1M views",

    ShortThumbnail4: "./src/pages/YT front page/components/videoAssets/Popcorners.jpg",
    ShortTitle4: "SNACKS, YO! #Popcornersbreakingbad",
    ShortViews4: "2M views",
}